name: Integration
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        machines: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: npm ci

      - name: Test
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
