name: Integration
on: [pull_request]
jobs:
  cypress:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        machines: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          start: npm run test:integration:run
